/**
 *
 * Copyright 2010 TeleNav, Inc. All rights reserved.
 * ITnMediaListener.java
 *
 */
package com.telenav.media;

/**
 * ITnMediaListener is the interface for receiving asynchronous events generated by players or recorders. Applications
 * may implement this interface and register their implementations with the setListener method in {@link TnMediaPlayer}
 * or {@link TnMediaRecorder}.
 * 
 * @author fqming (fqming@telenav.cn)
 *@date Jul 26, 2010
 */
public interface ITnMediaListener
{
    /**
     * Called when the media is ready for playback.
     */
    public final static String ON_PREPARE = "on_prepare";

    /**
     * Called to indicate an error.
     */
    public final static String ON_ERROR = "on_error";

    /**
     * Called to indicate an info or a warning.
     */
    public final static String ON_INFO = "on_info";

    /**
     * Called when the end of a media source is reached during playback.
     */
    public final static String ON_COMPLETION = "on_completion";

    /**
     * Called when the player or recorder is closed.
     */
    public final static String ON_CLOSE = "on_close";

    /**
     * This method is called to deliver an event to a registered listener when a Player event is observed.
     * 
     * @param player The player which generated the event.
     * @param event The event generated as defined by the enumerated types.
     * @param eventData The associated event data.
     */
    public void mediaUpdate(TnMediaPlayer player, String event, Object eventData);
}
